<?php

declare(strict_types=1);

namespace PestWP\Installer;

use RuntimeException;

/**
 * Generates WordPress test configuration files.
 *
 * This class creates the necessary configuration files for running
 * WordPress tests with SQLite database support.
 */
final class ConfigGenerator
{
    private string $wpPath;

    private string $pestPath;

    public function __construct(string $wpPath, string $pestPath)
    {
        $this->wpPath = $wpPath;
        $this->pestPath = $pestPath;
    }

    /**
     * Check if wp-tests-config.php and wp-config.php exist.
     */
    public function configExists(): bool
    {
        return file_exists($this->getConfigPath())
            && file_exists($this->getWpConfigPath());
    }

    /**
     * Get the path to wp-config.php in the WordPress directory.
     */
    public function getWpConfigPath(): string
    {
        return $this->wpPath . DIRECTORY_SEPARATOR . 'wp-config.php';
    }

    /**
     * Get the path to wp-tests-config.php.
     */
    public function getConfigPath(): string
    {
        return $this->pestPath . DIRECTORY_SEPARATOR . 'wp-tests-config.php';
    }

    /**
     * Get the path to the WordPress test library.
     */
    public function getTestLibraryPath(): string
    {
        return $this->pestPath . DIRECTORY_SEPARATOR . 'wordpress-tests-lib';
    }

    /**
     * Generate the wp-tests-config.php file.
     *
     * @param  bool  $force  Force regeneration
     *
     * @throws RuntimeException If generation fails
     */
    public function generate(bool $force = false): void
    {
        if ($this->configExists() && ! $force) {
            return;
        }

        $this->ensureDirectoryExists(dirname($this->getConfigPath()));
        $this->writeConfig();
        $this->downloadTestSuite();
    }

    /**
     * Write the configuration file.
     *
     * @throws RuntimeException If write fails
     */
    private function writeConfig(): void
    {
        // Write wp-tests-config.php
        $content = $this->generateConfigContent();

        if (file_put_contents($this->getConfigPath(), $content) === false) {
            throw new RuntimeException('Failed to write wp-tests-config.php');
        }

        // Write wp-config.php
        $wpConfigContent = $this->generateWpConfigContent();

        if (file_put_contents($this->getWpConfigPath(), $wpConfigContent) === false) {
            throw new RuntimeException('Failed to write wp-config.php');
        }
    }

    /**
     * Generate the configuration file content.
     */
    private function generateConfigContent(): string
    {
        $wpPath = str_replace('\\', '/', $this->wpPath);
        $pestPath = str_replace('\\', '/', $this->pestPath);
        $dbPath = $pestPath . '/database/.ht.sqlite';

        return <<<PHP
<?php
/**
 * WordPress test configuration file.
 *
 * This file is auto-generated by PestWP for SQLite-based testing.
 */

// Test WordPress installation path
define( 'ABSPATH', '{$wpPath}/' );

// Test with WordPress debug mode
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );

// SQLite Database Configuration
// Note: When using SQLite, these MySQL constants are still required
// but will be ignored by the SQLite drop-in
define( 'DB_NAME', 'wordpress_test' );
define( 'DB_USER', '' );
define( 'DB_PASSWORD', '' );
define( 'DB_HOST', '' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

// SQLite specific settings
define( 'USE_SQLITE', true );
define( 'SQLITE_DB_PATH', '{$dbPath}' );

// Table prefix for tests
\$table_prefix = 'wptests_';

// Test domain
define( 'WP_TESTS_DOMAIN', 'example.org' );
define( 'WP_TESTS_EMAIL', 'admin@example.org' );
define( 'WP_TESTS_TITLE', 'Test Blog' );
define( 'WP_TESTS_NETWORK_TITLE', 'Test Network' );

// PHP mail function return
define( 'WP_PHP_BINARY', 'php' );

// Language
define( 'WPLANG', '' );

// Multisite
define( 'WP_TESTS_MULTISITE', false );

// Directory settings
define( 'WP_TESTS_DIR', '{$pestPath}/wordpress-tests-lib' );
define( 'WP_CONTENT_DIR', '{$wpPath}/wp-content' );
define( 'WP_PLUGIN_DIR', '{$wpPath}/wp-content/plugins' );

// Security keys (test values)
define( 'AUTH_KEY', 'test-auth-key' );
define( 'SECURE_AUTH_KEY', 'test-secure-auth-key' );
define( 'LOGGED_IN_KEY', 'test-logged-in-key' );
define( 'NONCE_KEY', 'test-nonce-key' );
define( 'AUTH_SALT', 'test-auth-salt' );
define( 'SECURE_AUTH_SALT', 'test-secure-auth-salt' );
define( 'LOGGED_IN_SALT', 'test-logged-in-salt' );
define( 'NONCE_SALT', 'test-nonce-salt' );
PHP;
    }

    /**
     * Generate the wp-config.php content for the WordPress directory.
     */
    private function generateWpConfigContent(): string
    {
        $wpPath = str_replace('\\', '/', $this->wpPath);
        $pestPath = str_replace('\\', '/', $this->pestPath);
        $dbPath = $pestPath . '/database/.ht.sqlite';

        return <<<PHP
<?php
/**
 * WordPress configuration file for PestWP testing.
 *
 * This file is auto-generated by PestWP for SQLite-based testing.
 * DO NOT EDIT THIS FILE MANUALLY.
 */

// SQLite Database Configuration
if ( ! defined( 'DB_NAME' ) ) {
    define( 'DB_NAME', 'wordpress_test' );
}
if ( ! defined( 'DB_USER' ) ) {
    define( 'DB_USER', '' );
}
if ( ! defined( 'DB_PASSWORD' ) ) {
    define( 'DB_PASSWORD', '' );
}
if ( ! defined( 'DB_HOST' ) ) {
    define( 'DB_HOST', '' );
}
if ( ! defined( 'DB_CHARSET' ) ) {
    define( 'DB_CHARSET', 'utf8mb4' );
}
if ( ! defined( 'DB_COLLATE' ) ) {
    define( 'DB_COLLATE', '' );
}

// SQLite specific settings
if ( ! defined( 'USE_SQLITE' ) ) {
    define( 'USE_SQLITE', true );
}
if ( ! defined( 'SQLITE_DB_PATH' ) ) {
    define( 'SQLITE_DB_PATH', '{$dbPath}' );
}

// Table prefix for tests - THIS MUST BE A GLOBAL VARIABLE
// WordPress expects \$table_prefix in the global scope when wp-settings.php loads
global \$table_prefix;
if ( isset( \$GLOBALS['table_prefix'] ) ) {
    \$table_prefix = \$GLOBALS['table_prefix'];
} else {
    \$table_prefix = 'wptests_';
}

// WordPress debugging (only define if not already defined)
if ( ! defined( 'WP_DEBUG' ) ) {
    define( 'WP_DEBUG', true );
}
if ( ! defined( 'WP_DEBUG_LOG' ) ) {
    define( 'WP_DEBUG_LOG', false );
}
if ( ! defined( 'WP_DEBUG_DISPLAY' ) ) {
    define( 'WP_DEBUG_DISPLAY', false );
}

// Security keys (test values - do not use in production)
if ( ! defined( 'AUTH_KEY' ) ) {
    define( 'AUTH_KEY', 'test-auth-key-' . md5(__FILE__) );
}
if ( ! defined( 'SECURE_AUTH_KEY' ) ) {
    define( 'SECURE_AUTH_KEY', 'test-secure-auth-key-' . md5(__FILE__) );
}
if ( ! defined( 'LOGGED_IN_KEY' ) ) {
    define( 'LOGGED_IN_KEY', 'test-logged-in-key-' . md5(__FILE__) );
}
if ( ! defined( 'NONCE_KEY' ) ) {
    define( 'NONCE_KEY', 'test-nonce-key-' . md5(__FILE__) );
}
if ( ! defined( 'AUTH_SALT' ) ) {
    define( 'AUTH_SALT', 'test-auth-salt-' . md5(__FILE__) );
}
if ( ! defined( 'SECURE_AUTH_SALT' ) ) {
    define( 'SECURE_AUTH_SALT', 'test-secure-auth-salt-' . md5(__FILE__) );
}
if ( ! defined( 'LOGGED_IN_SALT' ) ) {
    define( 'LOGGED_IN_SALT', 'test-logged-in-salt-' . md5(__FILE__) );
}
if ( ! defined( 'NONCE_SALT' ) ) {
    define( 'NONCE_SALT', 'test-nonce-salt-' . md5(__FILE__) );
}

// Absolute path to the WordPress directory
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

// Sets up WordPress vars and included files
require_once ABSPATH . 'wp-settings.php';
PHP;
    }

    /**
     * Download the WordPress test suite library.
     *
     * @throws RuntimeException If download fails
     */
    private function downloadTestSuite(): void
    {
        $testLibPath = $this->getTestLibraryPath();

        if (is_dir($testLibPath)) {
            return; // Already exists
        }

        $this->ensureDirectoryExists($testLibPath);

        // Download from WordPress SVN
        $svnUrl = 'https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/';
        $this->downloadTestFiles($svnUrl, $testLibPath . DIRECTORY_SEPARATOR . 'includes');

        // Also download the data directory
        $dataUrl = 'https://develop.svn.wordpress.org/trunk/tests/phpunit/data/';
        $this->downloadTestFiles($dataUrl, $testLibPath . DIRECTORY_SEPARATOR . 'data');
    }

    /**
     * Download test files from WordPress SVN.
     * Note: This is a simplified implementation. In production, we might want to
     * download a zip or use a more robust method.
     */
    private function downloadTestFiles(string $baseUrl, string $destination): void
    {
        $this->ensureDirectoryExists($destination);

        // For now, we'll download the most critical files
        // A full implementation would recursively download all files
        $criticalFiles = [
            'includes/bootstrap.php',
            'includes/functions.php',
            'includes/install.php',
            'includes/testcase.php',
            'includes/factory.php',
            'includes/abstract-testcase.php',
        ];

        $baseDownloadUrl = 'https://raw.githubusercontent.com/WordPress/wordpress-develop/trunk/tests/phpunit/';

        foreach ($criticalFiles as $file) {
            $fileUrl = $baseDownloadUrl . $file;
            $localPath = $this->getTestLibraryPath() . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $file);

            $this->ensureDirectoryExists(dirname($localPath));
            $this->downloadFile($fileUrl, $localPath);
        }
    }

    /**
     * Download a single file.
     */
    private function downloadFile(string $url, string $destination): void
    {
        $context = stream_context_create([
            'http' => [
                'timeout' => 30,
                'user_agent' => 'PestWP/1.0',
            ],
        ]);

        $content = @file_get_contents($url, false, $context);
        if ($content !== false) {
            file_put_contents($destination, $content);
        }
    }

    /**
     * Ensure a directory exists.
     *
     * @throws RuntimeException If creation fails
     */
    private function ensureDirectoryExists(string $path): void
    {
        if (! is_dir($path)) {
            if (! mkdir($path, 0755, true)) {
                throw new RuntimeException('Failed to create directory: ' . $path);
            }
        }
    }
}
