<?php

declare(strict_types=1);

namespace PestWP\Commands;

use PestWP\Installer\Installer;
use RuntimeException;

use function dirname;
use function file_exists;
use function file_put_contents;
use function is_dir;
use function mkdir;
use function sprintf;

/**
 * Command to serve a WordPress instance for browser testing.
 *
 * Uses PHP's built-in web server to serve the WordPress installation
 * from .pest/wordpress directory, enabling browser tests without
 * requiring an external WordPress setup.
 */
class ServeCommand
{
    private string $basePath;

    private string $host;

    private int $port;

    private Installer $installer;

    /**
     * Default admin credentials for the test environment.
     */
    public const DEFAULT_ADMIN_USER = 'admin';

    public const DEFAULT_ADMIN_PASSWORD = 'password';

    public const DEFAULT_ADMIN_EMAIL = 'admin@example.org';

    public function __construct(
        ?string $basePath = null,
        string $host = 'localhost',
        int $port = 8080,
    ) {
        $this->basePath = $basePath ?? (getcwd() ?: dirname(__DIR__, 2));
        $this->host = $host;
        $this->port = $port;
        $this->installer = new Installer($this->basePath);
    }

    /**
     * Get the base URL for the server.
     */
    public function getBaseUrl(): string
    {
        return sprintf('http://%s:%d', $this->host, $this->port);
    }

    /**
     * Get the WordPress installation path.
     */
    public function getWordPressPath(): string
    {
        return $this->installer->getWordPressPath();
    }

    /**
     * Get the .pest directory path.
     */
    public function getPestPath(): string
    {
        return $this->installer->getPestPath();
    }

    /**
     * Check if WordPress is installed and ready to serve.
     */
    public function isReady(): bool
    {
        return $this->installer->isInstalled();
    }

    /**
     * Ensure WordPress is installed.
     *
     * @param callable|null $onProgress Progress callback
     */
    public function ensureInstalled(?callable $onProgress = null): void
    {
        if (! $this->isReady()) {
            $this->installer->install(false, $onProgress);
        }
    }

    /**
     * Create the router script for PHP built-in server.
     *
     * This script handles URL rewriting to mimic Apache/Nginx behavior
     * for WordPress pretty permalinks.
     */
    public function createRouterScript(): string
    {
        $routerPath = $this->installer->getPestPath() . '/router.php';
        $wpPath = str_replace('\\', '/', $this->installer->getWordPressPath());

        $routerContent = <<<PHP
<?php
/**
 * PestWP Router Script for PHP Built-in Server
 *
 * This script mimics Apache/Nginx URL rewriting for WordPress.
 * Auto-generated by PestWP ServeCommand.
 */

\$wpPath = '{$wpPath}';

// Get the request URI
\$uri = urldecode(parse_url(\$_SERVER['REQUEST_URI'], PHP_URL_PATH) ?? '/');

// Serve static files directly
\$filePath = \$wpPath . \$uri;
if (\$uri !== '/' && file_exists(\$filePath) && !is_dir(\$filePath)) {
    // Let PHP serve the file with proper MIME type
    return false;
}

// Handle WordPress requests through index.php
\$_SERVER['PHP_SELF'] = '/index.php';
\$_SERVER['SCRIPT_NAME'] = '/index.php';
\$_SERVER['SCRIPT_FILENAME'] = \$wpPath . '/index.php';

// Change to WordPress directory
chdir(\$wpPath);

// Include WordPress
require \$wpPath . '/index.php';
PHP;

        $dir = dirname($routerPath);
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        if (file_put_contents($routerPath, $routerContent) === false) {
            throw new RuntimeException('Failed to create router script');
        }

        return $routerPath;
    }

    /**
     * Get the command to start the PHP built-in server.
     *
     * @return array{command: string, workdir: string, router: string}
     */
    public function getServerCommand(): array
    {
        $routerPath = $this->createRouterScript();
        $wpPath = $this->installer->getWordPressPath();

        return [
            'command' => sprintf(
                'php -S %s:%d -t "%s" "%s"',
                $this->host,
                $this->port,
                $wpPath,
                $routerPath,
            ),
            'workdir' => $wpPath,
            'router' => $routerPath,
        ];
    }

    /**
     * Check if a port is available.
     */
    public function isPortAvailable(): bool
    {
        $socket = @fsockopen($this->host, $this->port, $errno, $errstr, 1);

        if ($socket !== false) {
            fclose($socket);

            return false; // Port is in use
        }

        return true; // Port is available
    }

    /**
     * Find an available port starting from the configured port.
     */
    public function findAvailablePort(int $maxAttempts = 10): int
    {
        $port = $this->port;

        for ($i = 0; $i < $maxAttempts; $i++) {
            $socket = @fsockopen($this->host, $port, $errno, $errstr, 1);

            if ($socket === false) {
                $this->port = $port;

                return $port;
            }

            fclose($socket);
            $port++;
        }

        throw new RuntimeException(
            sprintf('No available port found between %d and %d', $this->port, $port - 1)
        );
    }

    /**
     * Generate a .env file for browser testing configuration.
     */
    public function generateEnvFile(): string
    {
        $envPath = $this->basePath . '/.env.testing';
        $envContent = sprintf(
            <<<'ENV'
# PestWP Browser Testing Configuration
# Auto-generated by pest-wp-serve

WP_BASE_URL=%s
WP_ADMIN_USER=%s
WP_ADMIN_PASSWORD=%s
ENV,
            $this->getBaseUrl(),
            self::DEFAULT_ADMIN_USER,
            self::DEFAULT_ADMIN_PASSWORD,
        );

        if (file_put_contents($envPath, $envContent) === false) {
            throw new RuntimeException('Failed to create .env.testing file');
        }

        return $envPath;
    }

    /**
     * Get status information about the server.
     *
     * @return array{ready: bool, url: string, wordpress_path: string, host: string, port: int}
     */
    public function getStatus(): array
    {
        return [
            'ready' => $this->isReady(),
            'url' => $this->getBaseUrl(),
            'wordpress_path' => $this->installer->getWordPressPath(),
            'host' => $this->host,
            'port' => $this->port,
        ];
    }

    /**
     * Get the host.
     */
    public function getHost(): string
    {
        return $this->host;
    }

    /**
     * Get the port.
     */
    public function getPort(): int
    {
        return $this->port;
    }
}
