<?php

declare(strict_types=1);

namespace PestWP\Functions;

use RuntimeException;

/**
 * Get the browser configuration from tests/Pest.php.
 *
 * @return array{base_url: string, admin_user: string, admin_password: string}
 */
function getBrowserConfig(): array
{
    // Try to get config from Pest configuration
    if (function_exists('browser')) {
        return browser();
    }

    // Fallback to environment variables with type safety
    $baseUrl = $_ENV['WP_BASE_URL'] ?? getenv('WP_BASE_URL');
    $adminUser = $_ENV['WP_ADMIN_USER'] ?? getenv('WP_ADMIN_USER');
    $adminPassword = $_ENV['WP_ADMIN_PASSWORD'] ?? getenv('WP_ADMIN_PASSWORD');

    $config = [
        'base_url' => is_string($baseUrl) && $baseUrl !== '' ? $baseUrl : 'http://localhost:8080',
        'admin_user' => is_string($adminUser) && $adminUser !== '' ? $adminUser : 'admin',
        'admin_password' => is_string($adminPassword) && $adminPassword !== '' ? $adminPassword : 'password',
    ];

    return $config;
}

/**
 * Get the storage state path for authenticated sessions.
 */
function getStorageStatePath(): string
{
    $projectRoot = dirname(__DIR__, 2);
    $statePath = $projectRoot . '/.pest/state/admin.json';

    return $statePath;
}

/**
 * Check if browser authentication state exists.
 */
function hasBrowserAuthState(): bool
{
    $statePath = getStorageStatePath();

    return file_exists($statePath);
}

/**
 * Get Playwright command to run with authentication state.
 *
 * This helper generates the appropriate playwright command
 * that loads the pre-authenticated state.
 */
function getPlaywrightCommand(string $testFile = ''): string
{
    $statePath = getStorageStatePath();

    if (! hasBrowserAuthState()) {
        throw new RuntimeException(
            "Authentication state not found at: {$statePath}\n" .
            "Run 'npm run test:browser' first to generate the authentication state.",
        );
    }

    $command = 'npx playwright test';

    if ($testFile !== '') {
        $command .= " {$testFile}";
    }

    return $command;
}

/**
 * Helper to generate Playwright test boilerplate that uses authentication.
 *
 * This generates TypeScript code for a Playwright test that will
 * automatically use the saved authentication state.
 *
 * @param  string  $testName  Name of the test
 * @param  string  $url  WordPress admin URL to visit (relative to base URL)
 * @return string TypeScript test code
 */
function generatePlaywrightTest(string $testName, string $url = '/wp-admin/'): string
{
    $config = getBrowserConfig();
    $baseUrl = $config['base_url'];

    return <<<TS
import { test, expect } from '@playwright/test';

/**
 * {$testName}
 * 
 * This test uses pre-authenticated state saved by global-setup.ts
 * No manual login required - the test starts already authenticated.
 */
test('{$testName}', async ({ page }) => {
  // Navigate to WordPress admin (already authenticated)
  await page.goto('{$url}');
  
  // Verify we're on the admin page (not redirected to login)
  await expect(page).toHaveURL(/wp-admin/);
  
  // Add your test assertions here
  // Example: Check for WordPress admin bar
  await expect(page.locator('#wpadminbar')).toBeVisible();
});

TS;
}

/**
 * Helper to document browser() function for user reference.
 *
 * Returns documentation string explaining how to use browser config.
 */
function getBrowserConfigDocumentation(): string
{
    return <<<'DOC'
/*
|--------------------------------------------------------------------------
| Browser Testing Configuration
|--------------------------------------------------------------------------
|
| This configuration is used by Playwright for browser testing.
| It's automatically generated by `pest-setup-browser` command.
|
| To use in your Playwright tests:
|
|   1. Ensure you've run: npm install
|   2. Install browsers: npm run playwright:install
|   3. Run tests: npm run test:browser
|
| The global-setup.ts script will use these credentials to authenticate
| once, then save the session state for all tests to reuse.
|
| Environment Variables (alternative):
|   WP_BASE_URL - Base URL of your WordPress installation
|   WP_ADMIN_USER - WordPress admin username
|   WP_ADMIN_PASSWORD - WordPress admin password
|
*/

DOC;
}
